-- M3: persist the most recent HostState / HostInfo JSON per agent.
-- SQLite does not support `ADD COLUMN IF NOT EXISTS`, so these columns
-- are added idempotently from `DatabaseBackend::run_migrations`.
